-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 18:49:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testify_chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testify_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testify_chat` DEFAULT CHARACTER SET utf8 ;
USE `testify_chat` ;

-- -----------------------------------------------------
-- Table `testify_chat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testify_chat`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testify_chat`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testify_chat`.`rooms` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testify_chat`.`user_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testify_chat`.`user_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` VARCHAR(36) NOT NULL,
  `rooms_id` VARCHAR(36) NOT NULL,
  `blocked` TINYINT NOT NULL DEFAULT 0,
  `creator` TINYINT NOT NULL DEFAULT 0,
  `block_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_room_user_idx` (`users_id` ASC),
  INDEX `fk_user_room_rooms1_idx` (`rooms_id` ASC),
  CONSTRAINT `fk_user_room_user`
    FOREIGN KEY (`users_id`)
    REFERENCES `testify_chat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_room_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `testify_chat`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testify_chat`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testify_chat`.`messages` (
  `id` VARCHAR(36) NOT NULL,
  `text` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `rooms_id` VARCHAR(36) NOT NULL,
  `users_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idmessages_UNIQUE` (`id` ASC),
  INDEX `fk_messages_rooms1_idx` (`rooms_id` ASC),
  INDEX `fk_messages_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_messages_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `testify_chat`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `testify_chat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
